### ISSUE TITLE
Do you have a diff against Bootstrap 3.1.1? 

### ISSUE THREAD

**Issue by NacreData** [mrhanlon/twbs-dropdown-doubletap#3]
I'd like to help update this (and use it) with the lastest Bootstrap. I have a feeling that would be trivial if I had a copy of Bootstrap 3.1.1 to diff this against, then apply those changes (and perhaps debug) with the lastest Bootstrap. Does anyone have such a diff or a copy of Bootstrap 3.1.1. It doesn't appear to me that the releases are tagged in the Bootstrap github repo.

**Comment by NacreData** [comment]
Hm. looks like this is the diff? : 

@@ -1,5 +1,5 @@
 /* ========================================================================
- * Bootstrap: dropdown.js v3.1.1
+ * Bootstrap: dropdown-doubletap.js v3.1.1
  * http://getbootstrap.com/javascript/#dropdowns
  * ========================================================================
  * Copyright 2011-2014 Twitter, Inc.
@@ -45,9 +45,8 @@
         .trigger('shown.bs.dropdown', relatedTarget)
 
       $this.focus()
+      return false
     }
-
-    return false
   }
 
   Dropdown.prototype.keydown = function (e) {
@@ -144,4 +143,4 @@
     .on('click.bs.dropdown.data-api', toggle, Dropdown.prototype.toggle)
     .on('keydown.bs.dropdown.data-api', toggle + ', [role=menu], [role=listbox]', Dropdown.prototype.keydown)
 
-}(jQuery);
+}(jQuery);

**Comment by NacreData** [comment]
Pull Request submitted: https://github.com/mrhanlon/twbs-dropdown-doubletap/pull/4

**Comment by mrhanlon** [comment]
Closing.
